### ISSUE TITLE
Doesn't work (?)

### ISSUE THREAD

**Issue by FlySlime** [Colonial-Dev/WayAFK#2]
Hey!

I've tried playing around with this plugin for a couple of hours now and I can't get it to work. I've tried setting the config file to 3 seconds to see if it would work, no results... Then I opened up the file and changed both the config and the timeout variable in the code to 3 seconds, and it still didn't work. I've of course tried restarting Discord and it still doesn't work. I've disabled all other extensions also.

Is this verified to be working as of late? If so, how do I check logs for the plugin to debug further? Timeout = 600 doesn't seem to work either.

Thanks.

Information:
- Arch Linux, using ``discord`` package
- Gnome 44 Wayland

**Comment by FlySlime** [comment]
Wait, it seems like I am getting notifications on my phone despite Discord still showcasing my status as "Online", not "Idle". I will experiment a little more.

**Comment by FlySlime** [comment]
It seems like the extension works, but at the same doesn't work. It doesn't set my status to idle, but I do get phone notifications after the set time. Was this the intended behavior?

**Comment by Colonial-Dev** [comment]
I didn't bother to mess with the status, since just reporting AFK-ness is sufficient for notifications to hit your phone.

Also, are you sure you aren't going idle? It's basically impossible to observe the change independently IME.

**Comment by FlySlime** [comment]
I went AFK for a little while and noticed that I got notifications on my phone, something that I hadn't gotten in a couple of days due to the Wayland bug. I later tried with a friend to see if the timer worked, and it did. So it seems like it is working, but it is not changing my status from what I can see. I'm going idle, without the yellow icon pretty much lol.

**Comment by Colonial-Dev** [comment]
Got it, sounds good.

I'm going to run my own experiment to check if my status changes to idle within ~10 minutes. Hopefully it should be easy to add a "switch to idle" in the code - no reason *not* to do it.

**Comment by FlySlime** [comment]
Reporting back that I found another plugin that is nice to complement with this plugin. This plugin sets your status to idle after a set time, which is nice.
- https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK

**Comment by Colonial-Dev** [comment]
Oh nice, I'll take a peek later. I looked around for a way to set the user status from a plugin and couldn't find anything - must have missed that. Thanks!
