### ISSUE TITLE
Doesn't intercept keyboard/mouse activity when running in Flatpak/Wayland

### ISSUE THREAD

**Issue by asherbig** [Colonial-Dev/WayAFK#3]
I'm not sure what exactly causes it, but I use wayland and flatpak, which both aim to isolate the app. Wayland probably does more to isolate discord when it's running than flatpak.

Behavior:
When I'm interacting IN DISCORD, the WayAFK plugin works as expected. But if I'm not clicking/tying in the discord window, then WayAFK thinks I'm AFK.

**Comment by Colonial-Dev** [comment]
I may be misunderstanding, but it sounds like it's working as designed. This plugin is a hack:
> On startup, WayAFK subscribes to the `keydown` and `mousedown` events. Whenever you press a key or use your mouse inside the Discord window, a timer will be reset.

It can't break Wayland or Flatpak's isolation, unfortunately.

**Comment by asherbig** [comment]
Oh I see, I missed that. I'll close

**Comment by Colonial-Dev** [comment]
FWIW, if you're *immediately* going AFK when not typing/clicking, check the plugin settings and make sure the timeout didn't somehow wind up zeroed.
